export enum NameServices {
  PLAYER_SERVCE = 'PLAYER_SERVICE',
  OPERATOR_SERVICE = 'OPERATOR_SERVICE',
  // CHIP_SERVICE = 'CHIP_SERVICE',
  CURRENCY_SERVICE = 'CURRENCY_SERVICE',
  REPORT_SERVICE = 'REPORT_SERVICE',
  MS_GAMES_QUEUE = 'ms_games_queque',
}
