export enum TYPESOLUTION {
  NIL = -1,
  NOT_BETS = 0,
  BETS_NOT_STRAIGHT = 1,
  BETS_STRAIGHT = 2,
  NOT_BETS_AND_BETS_NOT_STRAIGHT = 3,
  NOT_BETS_AND_BETS_STRAIGHT = 4,
  BETS_NOT_STRAIGHT_AND_BETS_STRAIGHT = 5,
  ALL = 6,
}
