name: Build and Deploy dev

on:
  push:
    branches: ['dev']

jobs:
  build:
    name: Build and Deploy commit ${{github.sha}}
#    if: "contains(toJSON(github.event.commits.*.message), '[deploy]')"
    runs-on: ubuntu-latest
    steps:
      - name: ssh pipelines
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_DEV_USERNAME }}
          password: ${{ secrets.SSH_DEV_PASSWORD }}
          port: 22
          connect_timeout: 10s
          script: |
            echo "Deploying commit: ${{github.sha}}"
            sh /home/soporte/docker/actualizar_roulette_services.sh
